channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - param
  - datashader
  - bokeh
  - holoviews
  - panel
  - hvplot
  - intake
  - intake-parquet
  - fastparquet
  - python-snappy
  - s3fs
  - pip:
    - git+https://github.com/pyviz/jupyter-panel-proxy.git@jsignell/glob
